[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "FeedTracker"

[project.scripts]
feedtracker-gui = "feedtracker.gui.main:main"

[dependency-groups]
tests = ["pytest", "pytest-cov"]